#!/bin/bash

######################################################
#						     
#	Skript zum Ändern von internen pdf-Seiten		                            			                             
#	mittels Pythonksript von https://github.com/lovasoa/pagelabels-py                       
#			                             
#			                             
######################################################

read -e -p "Beginn des neuen Zählungsabschnitts gemäß absoluter pdf-Seitennr.: " secbegin
read -e -p "Optional: abweichenden Stil der Zählung (roman lowercase, roman uppercase, letters lowercase, letters uppercase) : " style
if ["$style" == ""]; then style="arabic"; fi
read -e -p "Optional: Präfix eingeben (z.B. fm für frontmatter): " prefix
read -e -p "Optional: abweichenden Nummerierungsbeginn (z.B. 3 statt 1) eingeben: " numbegin
if ["$numbegin" == ""]; then numbegin=1; fi

~/bin/pagelabels-py/addpagelabels.py --startpage "$secbegin" --type "$style" --prefix "$prefix" --firstpagenum "$numbegin" "$1" 

read -e -p "Einen weiteren Zählungsabschnitt erfassen? (j/n) " anotherone

while [ "$anotherone" == "j" ]; do

	read -e -p "Beginn des neuen Zählungsabschnitts gemäß absoluter pdf-Seitennr.: " secbegin
	read -e -p "Optional: abweichenden Stil der Zählung (roman lowercase, roman uppercase, letters lowercase, letters uppercase) : " style
		if ["$style" == ""]; then style="arabic"; fi
	read -e -p "Optional: Präfix eingeben (z.B. fm für frontmatter): " prefix
	read -e -p "Optional: abweichenden Nummerierungsbeginn (z.B. 3 statt 1) eingeben: " numbegin
		if ["$numbegin" == ""]; then numbegin=1; fi

	~/bin/pagelabels-py/addpagelabels.py --startpage $secbegin --type "$style" --prefix "$prefix" --firstpagenum $numbegin "$1"  

	read -e -p "Einen weiteren Zählungsabschnitt erfassen? (j/n) " anotherone

done

echo "Fertig!"

exit 0
